<html>
    <body>
        <div>
            <h1>Contact Us</h1>
            <form class="form" id="submit-query" action="<?php echo $this->getUrl("help/ContactUs/SubmitQuery")?>" method="post" autocomplete="off">
            Name:<input type="text" name="name" /><br/>
            Email:<input type="text" name="email" /><br/>
            Phone:<input type="text" name="phone" /><br/>
            Your Message:<textarea name="query" rows="4" cols="50"></textarea><br/></br>   
            <input type="submit" />
            </form>
    </div>
    </body>
</html>